/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class HelloWorldTest {
    
    @Mock
    Recipient recipient;

    @Test
    public void testGreet() {
        when(recipient.name()).thenReturn("Sam");
        HelloWorld subject = new HelloWorld(recipient);

        assertEquals("Hello, Sam", subject.greet());
    }
}
