/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class HelloWorldTest {
    @Test public void testGreet() {
        HelloWorld subject = new HelloWorld();
        assertEquals("Hello, Sam", subject.greet("Sam"));
    }
}
