/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class HelloWorld {
    private final Recipient recipient;

    public HelloWorld(Recipient recipient) {
        this.recipient = recipient;
    }

    public String greet() {
        return "Hello, " + recipient.name();
    }
}
